file: https://raw.githubusercontent.com/ory/hydra/v2.2.0/internal/httpclient/api/openapi.yaml
spec: oas3
envPrefix: HYDRA_ADMIN
patchBefore:
  - path: patch-before.yaml
    strategy: json6902
patchAfter:
  - path: patch-after.yaml
    strategy: json6902
