file: https://raw.githubusercontent.com/ory/hydra/v1.11.10/spec/swagger.json
spec: oas2
envPrefix: HYDRA_PUBLIC
patchBefore:
  - path: patch-before.yaml
    strategy: json6902
patchAfter:
  - path: patch-after.yaml
    strategy: json6902
